CREATE TABLE IF NOT EXISTS users(
    id UUID NOT NULL PRIMARY KEY  DEFAULT gen_random_uuid(),
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL  DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL  DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ad(
 id UUID NOT NULL PRIMARY KEY  DEFAULT gen_random_uuid(),
 ad_name TEXT NOT NULL,
 description TEXT,
 price INTEGER NOT NULL,
 author_id UUID REFERENCES users(id) ON DELETE CASCADE,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL  DEFAULT NOW(),
 updated_at TIMESTAMP WITH TIME ZONE NOT NULL  DEFAULT NOW()
)
